### ISSUE TITLE
Probs aethystool and details

### ISSUE THREAD

**Issue by cyberbook78** [aethys256/AethysTools#10]
i become this lua error

Message: ...face\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:832: NickTag 'GetNicknameTable' expects a string on #1 argument.
Time: Mon Dec  3 18:08:54 2018
Count: 1
Stack: ...face\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:832: NickTag 'GetNicknameTable' expects a string on #1 argument.
[C]: ?
[C]: in function `assert'
...face\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:832: in function `GetNicknameTable'
Interface\AddOns\AethysTools\NickTag.lua:36: in function `SetNickname'
Interface\AddOns\Details\gumps\janela_options.lua:4063: in function `func'
Interface\AddOns\Details\Libs\DF\textentry.lua:382: in function <Interface\AddOns\Details\Libs\DF\textentry.lua:370>

Locals: 

thx

**Comment by Mystler** [comment]
Right, Details/NickTag Lib was updated so that custom name overrides bypassing restrictions do not work anymore. I guess this module can be removed completely. (I opened a PR for that a while ago. https://github.com/aethys256/AethysTools/pull/7) For a quick fix, open AethysTools.toc and remove the line about NickTag.lua.

**Comment by aethys256** [comment]
Fixed in https://github.com/aethys256/AethysTools/commit/c86dbcdb45280164a7b334da9b9fd1daf52a1e2b, thanks @Mystler 👍
